
version: 2

sources:
    - name: staging
      #For bigquery:
      database: zoom-camp-project-23525

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: external_for_hire_vehicles_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}